# Generated by Django 5.0 on 2024-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='yeabsira', max_length=255),
            preserve_default=False,
        ),
    ]
