# Generated by Django 5.0 on 2024-04-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_registeredemails_subscribed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisteredEmails',
        ),
    ]
